# Generated by Django 2.1.7 on 2019-03-05 05:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情'),
        ),
    ]
